/*
 * API Support - Supply Chain Finance - Seller Credit Order V1
 * Support API for Seller Credit  The microservice is responsible for saving information on the header of the supplier credit order and the detail of the supplier credit order. <br/><br/> <b>Business area </b>`Operations and Execution`<br> <b>Business domain </b>`Trade Banking`<br> <b>Service domain </b>`Credit Facility`<br> 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: ardmarti@pichincha.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ec.com.poc.sellercredit.dto;


import java.util.Objects;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class CounterPart {

  private String identificationValue;
  private String description;

}

