spring:
  application:
    name: user-registration-app
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

password:
  pattern: '^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,20}$'



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  packages-to-scan: com.nisum.latam.infrastructure.input.adapter.rest.impl
  paths-to-match:
    - /api/**
logging:
  level:
    org.springdoc: DEBUG